"""empty message

Revision ID: 667e3bb30cb7
Revises: 02938fd433b6
Create Date: 2022-08-03 21:47:38.760910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667e3bb30cb7'
down_revision = '02938fd433b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable='False')
    op.alter_column('Artist', 'seeking_description',
               existing_type=sa.VARCHAR(length=120),
               nullable='True')
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking_talent')
    op.alter_column('Artist', 'seeking_description',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
